name: Android CI

on:
  push:
    branches: [ "master" , "Dev", "Feature" ]
  pull_request:
    branches: [ "master" , "Dev" , "Feature" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean Project
      run: ./gradlew clean
      
    # Add this step to create lint baseline if it doesn't exist
    - name: Create Lint Baseline
      run: ./gradlew updateLintBaseline -Dlint.baselines.continue=true
      continue-on-error: true
      
    # Add this step to check if baseline was created and commit it
    - name: Check and Commit Lint Baseline
      run: |
        if [ -f app/lint-baseline.xml ]; then
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add app/lint-baseline.xml
          git commit -m "Add/Update lint baseline" || echo "No changes to commit"
          git push || echo "No changes to push"
        fi
      continue-on-error: true

    - name: Build with Gradle
      run: ./gradlew assembleRelease -Dlint.baselines.continue=true
      
    - name: List APK Output Directory
      run: ls -R app/build/outputs/apk/
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: warn
        include-hidden-files: false
